NMC/Areas/Admin/Pages/Bookings/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Extensions;
using NMC.Models;
using NMC.Services;

namespace NMC.Areas.Admin.Pages.Bookings
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;
        private readonly ICacheManager cacheManager;

        public CreateModel(ILogger<CreateModel> logger, MedContext context, ICacheManager cacheManager)
        {
            this.logger = logger;
            this.context = context;
            this.cacheManager = cacheManager;
        }

        [BindProperty]
        public Booking Booking { get; set; }

        public SelectList DoctorsSelect { get; set; } 
        public SelectList WardsSelect { get; set; } 

        public async Task OnGet()
        {
            string lang = User.GetUserLanguage();
            bool isArabic = (lang == "ar");
            string typeNameStr = isArabic ? "ArName" : "EnName";
            DoctorsSelect = new SelectList(await cacheManager.GetReferrers(), "Id", "Name", Booking?.DoctorId);
            WardsSelect = new SelectList(await cacheManager.GetWards(), "Id", typeNameStr, Booking?.WardId);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                var now = DateTime.Now;
                Booking.CreatedOn = now;
                Booking.CreatedBy = User.GetUserName();
                Booking.ValidUntil = now.AddHours(16);
                Booking.Status = BookingStatus.Pending;
                context.Bookings.Add(Booking);
                await context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/Bookings/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Extensions;
using NMC.Models;
using NMC.Services;

namespace NMC.Areas.Admin.Pages.Bookings
{
    public class EditModel : PageModel
    {
        private readonly ILogger<EditModel> logger;
        private readonly MedContext context;
        private readonly ICacheManager cacheManager;

        public EditModel(ILogger<EditModel> logger, MedContext context, ICacheManager cacheManager)
        {
            this.logger = logger;
            this.context = context;
            this.cacheManager = cacheManager;
        }

        [BindProperty]
        public Booking Booking { get; set; }

        public SelectList DoctorsSelect { get; set; }

        public SelectList WardsSelect { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public async Task OnGetAsync()
        {
            Booking = await context.Bookings
                .Where(x => x.Id == Id)
                .FirstOrDefaultAsync();

            string lang = User.GetUserLanguage();
            bool isArabic = (lang == "ar");
            string typeNameStr = isArabic ? "ArName" : "EnName";
            DoctorsSelect = new SelectList(await cacheManager.GetReferrers(), "Id", "Name", Booking?.DoctorId);
            WardsSelect = new SelectList(await cacheManager.GetWards(), "Id", typeNameStr, Booking?.WardId);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                var entry = context.Bookings.Attach(Booking);
                entry.State = EntityState.Modified;
                await context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/Bookings/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using NMC.Data;
using NMC.Models;

namespace NMC.Areas.Admin.Pages.Bookings
{
    public class IndexModel : PageModel
    {
        private readonly MedContext context;

        public IndexModel(MedContext context)
        {
            this.context = context;
        }

        public IEnumerable<Booking> Bookings { get; set; }

        public async Task OnGet()
        {
            Bookings = await context.Bookings
                .Include(x => x.Ward)
                .Include(x => x.Doctor)
                .AsNoTracking().ToListAsync();

        }
    }
}

NMC/Areas/Admin/Pages/Bookings/SelectRoom.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Extensions;
using NMC.Models;
using NMC.Services;

namespace NMC.Areas.Admin.Pages.Bookings
{
    public class SelectRoomModel : PageModel
    {
        private readonly ILogger<SelectRoomModel> logger;
        private readonly MedContext context;
        private readonly ICacheManager cacheManager;

        public SelectRoomModel(ILogger<SelectRoomModel> logger, MedContext context, ICacheManager cacheManager)
        {
            this.logger = logger;
            this.context = context;
            this.cacheManager = cacheManager;
        }

        
        public Booking Booking { get; set; }

        public IEnumerable<Room> Rooms { get; set; }

        public SelectList WardsSelect { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Id { get; set; }

        public async Task OnGetAsync()
        {
            Booking = await context.Bookings
                .Where(x => x.Id == Id)
                .FirstOrDefaultAsync();

            string lang = User.GetUserLanguage();
            bool isArabic = (lang == "ar");
            string typeNameStr = isArabic ? "ArName" : "EnName";
            WardsSelect = new SelectList(await cacheManager.GetWards(), "Id", typeNameStr, Booking?.WardId);
        }

    }
}

NMC/Areas/Admin/Pages/Doctors/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Models;

namespace NMC.Areas.Admin.Pages.Doctors
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;

        public CreateModel(ILogger<CreateModel> logger, MedContext context)
        {
            this.logger = logger;
            this.context = context;
        }

        [BindProperty]
        public Doctor Doctor { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                context.Doctors.Add(Doctor);
                await context.SaveChangesAsync();
                
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/Patients/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Models;

namespace NMC.Areas.Admin.Pages.Patients
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;

        public CreateModel(ILogger<CreateModel> logger, MedContext context)
        {
            this.logger = logger;
            this.context = context;
        }

        [BindProperty]
        public Patient Patient { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                context.Patients.Add(Patient);
                await context.SaveChangesAsync();
                
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/RoomGrades/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Models;

namespace NMC.Areas.Admin.Pages.RoomGrades
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;

        public CreateModel(ILogger<CreateModel> logger, MedContext context)
        {
            this.logger = logger;
            this.context = context;
        }

        [BindProperty]
        public RoomGrade RoomGrade { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                context.RoomGrades.Add(RoomGrade);
                await context.SaveChangesAsync();
                
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/Rooms/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Extensions;
using NMC.Models;
using NMC.Services;

namespace NMC.Areas.Admin.Pages.Rooms
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;
        private readonly ICacheManager cacheManager;

        public CreateModel(ILogger<CreateModel> logger, MedContext context, ICacheManager cacheManager)
        {
            this.logger = logger;
            this.context = context;
            this.cacheManager = cacheManager;
        }

        [BindProperty]
        public Room Room { get; set; }

        public SelectList RoomGradesSelect { get; set; } 
        public SelectList WardsSelect { get; set; } 

        public async Task OnGet()
        {
            string lang = User.GetUserLanguage();
            bool isArabic = (lang == "ar");
            string typeNameStr = isArabic ? "ArName" : "EnName";
            RoomGradesSelect = new SelectList(await cacheManager.GetRoomGrades(), "Id", typeNameStr, Room?.RoomGradeId);
            WardsSelect = new SelectList(await cacheManager.GetWards(), "Id", typeNameStr, Room?.WardId);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                context.Rooms.Add(Room);
                await context.SaveChangesAsync();
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Areas/Admin/Pages/Wards/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using NMC.Data;
using NMC.Models;

namespace NMC.Areas.Admin.Pages.Wards
{
    public class CreateModel : PageModel
    {
        private readonly ILogger<CreateModel> logger;
        private readonly MedContext context;

        public CreateModel(ILogger<CreateModel> logger, MedContext context)
        {
            this.logger = logger;
            this.context = context;
        }

        [BindProperty]
        public Ward Ward { get; set; }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            try
            {
                context.Wards.Add(Ward);
                await context.SaveChangesAsync();
                
            }
            catch(Exception ex)
            {
                logger.LogError(ex.Message);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

NMC/Pages/BookingReasonTypes/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NMC.Data;
using NMC.Models;

namespace NMC.Pages.BookingReasonTypes
{
    public class CreateModel : PageModel
    {
        private readonly NmcContext context;

        public CreateModel(NmcContext context)
        {
            this.context = context;
        }

        [BindProperty]
        public BookingReasonType Entity { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; } = "/BookingReasonTypes";

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                try
                {
                    context.Set<BookingReasonType>().Add(Entity);
                    await context.SaveChangesAsync();
                    return Redirect(ReturnUrl);
                }
                catch (Exception ex)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                }
            }
            return Page();
        }
    }
}

NMC/Pages/Bookings/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NMC.Data;
using NMC.Extensions;
using NMC.Models;

namespace NMC.Pages.Bookings
{
    public class CreateModel : PageModel
    {
        private readonly NmcContext context;

        public CreateModel(NmcContext context)
        {
            this.context = context;
        }

        [BindProperty]
        public Booking Entity { get; set; } = new();

        public SelectList SelectReason { get; set; }
        public SelectList SelectDoctor { get; set; }

        [BindProperty(SupportsGet = true)]
        public string ReturnUrl { get; set; } = "/Bookings";

        public async Task InitDataAsync()
        {
            SelectReason = new SelectList(
                await context.BookingReasonTypes.ToListAsync(),
                "Id",
                User.IsArabic() ? "NameAr" : "Name",
                Entity?.ReasonId
                );

            SelectDoctor = new SelectList(
                await context.Doctors
                    .Where(x => x.IsReferrer)
                    .OrderBy(x => x.FirstName)
                    .AsNoTracking()
                    .ToListAsync(),
                "Id",
                "Name",
                Entity?.DoctorId
                );
        }

        public async Task OnGetAsync()
        {
            AppUser user = await context.Users.FindAsync(User.GetUserId());
            if(user.DoctorId.HasValue)
            {
                Entity.DoctorId = user.DoctorId.Value;
            }

            await InitDataAsync();
        }

        public async Task<IActionResult> OnPostAsync(string rooms = null)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Entity.CreatedBy = User.Identity.Name;
                    Entity.CreatedOn = DateTime.Now;
                    context.Set<Booking>().Add(Entity);
                    await context.SaveChangesAsync();
                    if (!string.IsNullOrEmpty(rooms)) return Redirect($"/Bookings/BookRooms/{Entity.Id}");
                    return Redirect(ReturnUrl);
                }
                catch (Exception ex)
                {
                    ViewData["ErrorMessage"] = ex.Message;
                }
            }
            await InitDataAsync();
            return Page();
        }
    }
}

NMC/Areas/AdmissionOffice/Pages/Bookings/ActiveBookings.cshtml
@page

@using Microsoft.EntityFrameworkCore

@{
    ViewBag.PageTitle = _localizer["Current Bookings"];
}

@functions{

    public string Lang { get; set; }
    public bool IsArabic => Lang?.ToLower() == "ar";

    public List<Room> Rooms { get; set; }
    public List<Ward> Wards { get; set; }
    public List<RoomAllocation> Allocations { get; set; }
    public DateTime From { get; set; }
    public DateTime To { get; set; }

    public async Task OnGetAsync()
    {
        Lang = User.GetUserLanguage();
        From = DateTime.Today;
        To = From.AddDays(7);
        await GetRooms();
    }

    private async Task GetRooms()
    {
        Rooms = (await _mem.GetRooms())?.ToList();
        Wards = (await _mem.GetWards())?.ToList().OrderBy(x => x.Floor).ThenBy(x => x.Code).ToList();
        Allocations = (await _ctx.RoomAllocations.Where(x => x.Date >= From && x.Date <= To).ToListAsync());

    }

}

<div class="content-fluid">
    @*<div class="row">
        <div class="col-sm-5 col-5">
            <h4 class="page-title">@ViewBag.PageTitle</h4>
        </div>
    </div>*@

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                
                <div class="card-body">
                    <h3 class="text-center mb-3">@_localizer["Active Bookings and Reservations"]</h3>
                    
                    <div class="table-responsive">
                        <table class="table text-nowrap text-center table-bordered table-hover">
                            <tr>
                                <th>@_localizer["Room"]</th>
                                @for (DateTime s = From; s <= To; s = s.AddDays(1))
                                {
                                    <th scope="col"><date value="@s" format="ddd MMM dd"></date></th>
                                }
                            </tr>
                            @foreach (var w in Wards)
                            {
                                var rooms = Rooms.Where(x => x.WardId == w.Id).OrderBy(x => x.Code).ToArray();
                                <tr>
                                    <td class="table-primary text-left" scope="colgroup" colspan="25">@(Model.IsArabic ? w.Name : w.Name)</td>
                                </tr>
                                @foreach (var r in rooms)
                                {
                                    int ndx = 0;
                                    <tr>
                                        <th scope="row">@r.Name</th>
                                        @for (DateTime s = From; s <= To; s = s.AddDays(1))
                                        {
                                            string color = "";
                                            string text = "";
                                            string css = ""; // "available";
                                            List<string> names = new();
                                            foreach (var aloc in Allocations.Where(x => x.RoomId == r.Id && x.Date == s))
                                            {
                                                if (aloc.Status == RoomStatus.Reserved)
                                                {
                                                    color = "table-danger";
                                                }
                                                else if (aloc.Status == RoomStatus.Booked)
                                                {
                                                    if (string.IsNullOrEmpty(color))
                                                    {
                                                        color = "table-warning";
                                                    }
                                                }

                                                names.Add(aloc.Text);
                                            }
                                            if (string.IsNullOrEmpty(color))
                                            {
                                                //color = "table-success";
                                            }
                                            <td class="@color @css" data-room="@r.Code" data-ndx="@ndx">@string.Join(',', names.Distinct())</td>

                                            ndx++;
                                        }
                                    </tr>
                                }
                            }

                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NMC/Areas/AdmissionOffice/Pages/Bookings/Index.cshtml
@page
@using Microsoft.EntityFrameworkCore

@{
    ViewBag.PageTitle = _localizer["Bookings"];
}

@functions{

    public IEnumerable<Booking> Items { get; set; }

    [TempData]
    public string AlertMessage { get; set; }

    public async Task OnGetAsync()
    {
        Items = await _mem.GetBookings();
    }

    public async Task<IActionResult> OnPostCancelAsync(int id)
    {
        var booking = await _ctx.Bookings
            .Include(x => x.Allocations).ThenInclude(x => x.Room)
            .Include(x => x.Doctor)
            .Where(x => x.Id == id)
            .FirstOrDefaultAsync();

        if (booking != null)
        {
            var tx = await _ctx.Database.BeginTransactionAsync();
            try
            {

                booking.Active = false;
                _ctx.RemoveRange(booking.Allocations);
                //_ctx.Bookings.Remove(booking);
                await _ctx.SaveChangesAsync();
                await tx.CommitAsync();
                _mem.Reset(nameof(Booking));
            }
            catch (Exception ex)
            {
                await tx.RollbackAsync();
            }

        }
        return RedirectToPage("./Index");
    }

    public async Task<IActionResult> OnPostConfirmAsync(int id)
    {
        var booking = await _ctx.Bookings
            .Include(x => x.Allocations).ThenInclude(x => x.Room)
            .Where(x => x.Id == id)
            .FirstOrDefaultAsync();

        if (booking != null)
        {
            var tx = await _ctx.Database.BeginTransactionAsync();
            try
            {
                foreach (var aloc in booking.Allocations)
                {
                    aloc.Status = RoomStatus.Reserved;
                }
                await _ctx.SaveChangesAsync();
                await tx.CommitAsync();
                _mem.Reset(nameof(Booking));
                //AlertMessage = $"Room '{booking.RoomNo}' is reserved to booking '{booking.Name}' between '{booking.From.ToString("ddd dd-MM-yyyy")}' and '{booking.To.ToString("ddd dd-MM-yyyy")}'";
            }
            catch (Exception ex)
            {
                await tx.RollbackAsync();
            }

        }
        return RedirectToPage("./Index");
    }
}

<div class="content">
    <div class="row">
        <div class="col-sm-5 col-5">
            <h4 class="page-title">@ViewBag.PageTitle</h4>
        </div>
        <div class="col-sm-7 col-7 text-right m-b-30">
            <a asp-page="./Create" class="btn btn-primary btn-rounded"><i class="fa fa-plus"></i> @_localizer["Create"]</a>
        </div>
    </div>

    @if (AlertMessage != null)
    {
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>Success!</strong> @AlertMessage
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
        </div>
    }

    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table text-nowrap table-striped custom-table mb-0 datatable">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().Name)</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().RequestDate)</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().Doctor.Name)</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().RoomNo)</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().From)</th>
                            <th>@Html.DisplayNameFor(p => p.Items.FirstOrDefault().To)</th>

                            <th class="text-center">@_localizer["Status"]</th>
                            <th class="text-center">@_localizer["Status Action"]</th>
                            @*<th class="text-right">@_localizer["Action"]</th>*@
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Items)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td><date value="@item.RequestDate"></date></td>
                                <td>@item.Doctor?.Name</td>
                                <td>@item.RoomNo</td>
                                <td><date value="@item.From"></date></td>
                                <td><date value="@item.To"></date></td>
                                <td class="text-center">@item.Status</td>
                                <td class="text-center">
                                    <button disabled="@(!item.CanBeCancelled)" data-toggle="modal" data-id="@item.Id" data-target="#cancel-booking" class="custom-badge clickable status-red text-danger" role="button">Cancel</button>
                                    <button hidden="@(item.Status == RoomStatus.Reserved)" data-toggle="modal" data-id="@item.Id" data-target="#confirm-booking" class="custom-badge status-blue  @(item.Status == RoomStatus.Reserved ? "disabled " : "clickable text-primary" )" role="button">Confirm</button>
                                    <a asp-page="../Inpatients/Create" asp-route-bookingId="@item.Id" class="custom-badge status-blue"  role="button">New Inpatient</a>
                                </td>
                                @*<td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" asp-page="./EditBooking" asp-route-id="@item.Id"><i class="fa fa-pencil m-r-5"></i> @_localizer["Edit"]</a>
                                        </div>
                                    </div>
                                </td>*@
                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<div id="cancel-booking" class="modal fade delete-modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img src="~/assets/img/sent.png" alt="" width="50" height="46">
                <h3>@_localizer["Are you sure want to cancel this"] @_localizer["booking"] @_localizer["?"]</h3>
                <div class="m-t-20">
                    <form method="post" asp-page-handler="cancel" asp-route-id="param-id">
                        <a href="#" class="btn btn-white" data-dismiss="modal">@_localizer["Close"]</a>
                        <button type="submit" class="btn btn-danger">@_localizer["Cancel"]</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="confirm-booking" class="modal fade delete-modal delete-modal" role="dialog">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body text-center">
                <img src="~/assets/img/sent.png" alt="" width="50" height="46">
                <h3>@_localizer["Are you sure want to confirm this"] @_localizer["booking"] @_localizer["?"]</h3>
                <div class="m-t-20">
                    <form method="post" asp-page-handler="confirm" asp-route-id="param-id">
                        <a href="#" class="btn btn-white" data-dismiss="modal">@_localizer["Close"]</a>
                        <button type="submit" class="btn btn-primary">@_localizer["Confirm"]</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts 
{
<script>
    $('#cancel-booking').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) 
        var itemId = button.data('id') // get item.Id
        var modal = $(this)
        var current = modal.find('.modal-body form').attr('action')
        current = current.replace('param-id', itemId)
        modal.find('.modal-body form').attr('action', current)
    })

    $('#confirm-booking').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget)
        var itemId = button.data('id') // get item.Id
        var modal = $(this)
        var current = modal.find('.modal-body form').attr('action')
        current = current.replace('param-id', itemId)
        modal.find('.modal-body form').attr('action', current)
    })
</script>
}